---
# dbt project configuration file
# refer: https://zenn.dev/foursue/books/31456a86de5bb4/viewer/7fce02)

name: 'dbt_training'
config-version: 2
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: [target, dbt_packages]

models:
  dbt_training:
    sources:  # models/sources folder
      +materialized: view
    marts:  # models/marts folder
      +materialized: table
